# .github/workflows/deploy_docs.yml
name: Deploy docs for main branch
on:
  push:
    branches:
      - main
jobs:
  deploy-preview:
    runs-on: ubuntu-22.04
    env:
      EODASH_MAPBOX_TOKEN: ${{ secrets.EODASH_MAPBOX_TOKEN }}
    permissions:
      contents: write
      pages: write
      pull-requests: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - run: |
          npm install
          npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .vitepress/dist/
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
